
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration - keys should be set in environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Check if Supabase is configured
const isSupabaseConfigured = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY;

if (!isSupabaseConfigured) {
  console.warn('⚠️ Supabase not configured. Authentication features will be disabled.');
}

// Create a safe Supabase client that won't crash if not configured
export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : createClient<Database>('https://placeholder.supabase.co', 'placeholder-key', {
      auth: { persistSession: false },
      realtime: { params: { eventsPerSecond: 0 } }
    });

// Export configuration status for components to check
export const isSupabaseEnabled = isSupabaseConfigured;
